// Disposable, local PostgreSQL only. Never connects to production.
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { readFile,readdir } from 'node:fs/promises';
import pg from 'pg';
import {createDatabase} from '../apps/api/dist/db/database.js';
import {PlaybackRepository} from '../apps/api/dist/playback/playback-repository.js';
import {PlaylistRepository} from '../apps/api/dist/playlists/playlist-repository.js';
import {PlaybackActivityProjector} from '../apps/api/dist/playback/playback-activity-projector.js';
import {encodeTrackReference} from '../apps/api/dist/music-source/track-reference.js';

const url=new URL(process.env.HIRMOS_TEST_DATABASE_URL??'');
assert.ok(['127.0.0.1','localhost'].includes(url.hostname)&&url.pathname==='/hirmos_core_test');
const admin=new pg.Client({connectionString:url.href});await admin.connect();
const schema=`hirmos_queue_${randomUUID().replaceAll('-','')}`;await admin.query(`CREATE SCHEMA ${schema}`);
url.searchParams.set('options',`-c search_path=${schema} -c statement_timeout=15000`);
const db=createDatabase(url.href);let count=0;const pass=s=>{count++;console.log(`PASS ${s}`);};
try {
  for(const file of (await readdir(new URL('../database/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort())await db.query(await readFile(new URL(`../database/migrations/${file}`,import.meta.url),'utf8'));
  const user=randomUUID(),other=randomUUID(),desktop=randomUUID(),mobile=randomUUID(),foreign=randomUUID();
  await db.query(`INSERT INTO users(id,email,display_name,role) VALUES($1,'queue@example.test','Queue','user'),($2,'other@example.test','Other','user')`,[user,other]);
  const source=(await db.query(`INSERT INTO music_sources(name,adapter_type,base_url,credential_ciphertext,encryption_key_version,enabled)
    VALUES('Synthetic','navidrome','https://music.example.test',decode('00','hex'),1,true) RETURNING id`)).rows[0].id;
  await db.query(`INSERT INTO catalog_tracks(source_id,remote_track_id,title,artist_name,album_name,duration_ms)
    SELECT $1,n::text,'Track '||n,'Artist','Album',180000 FROM generate_series(1,5001)n`,[source]);
  const repo=new PlaybackRepository(db),lists=new PlaylistRepository(db);
  for(const [uid,id] of [[user,desktop],[user,mobile],[other,foreign]])await repo.registerDevice({userId:uid,deviceId:id,name:'Fixture',type:'desktop'});
  const ref=n=>encodeTrackReference(source,String(n));
  const anchor=s=>({currentQueueItemId:s.currentQueueItemId,playbackInstanceId:s.playbackInstanceId,leaseEpoch:s.leaseEpoch,attempt:s.attempt});
  const command=(s,operation,deviceId=mobile)=>({userId:user,deviceId,commandId:randomUUID(),expectedRevision:s.revision,expectedQueueRevision:s.queueRevision,
    currentQueueItemId:s.currentQueueItemId,playbackInstanceId:s.playbackInstanceId,expectedStatus:s.status,operation});
  const ids=s=>s.queue.map(i=>Buffer.from(i.trackRef,'base64url').toString().split('\0')[1]);
  const start=async(tracks=['1','2','3'])=>{const before=await repo.snapshot(user);return (await repo.selectContext({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:before.revision,
    replaceQueueRevision:before.queueRevision,sourceId:source,remoteTrackIds:tracks,selectedIndex:0,contextType:'album',contextRef:'album'})).snapshot;};
  let s=await repo.snapshot(user);
  const prepared=await repo.editQueue(command(s,{action:'add',placement:'queue',trackRefs:[ref(1)]}));
  assert.equal(prepared.status,'accepted');s=prepared.snapshot;assert.equal(s.status,'stopped');assert.equal(s.activeDeviceId,null);assert.equal(s.currentQueueItemId,null);
  pass('adding to an empty queue prepares without sound or lease');
  const preparedOrder=s.queue.map(i=>i.id);
  const begin=command(s,{action:'select',itemId:s.queue[0].id},desktop);
  const begun=await repo.editQueue(begin);assert.equal(begun.status,'accepted');s=begun.snapshot;
  assert.equal(s.currentQueueItemId,preparedOrder[0]);assert.equal(s.status,'playing');assert.equal(s.activeDeviceId,desktop);
  assert.ok(s.playbackInstanceId);assert.deepEqual(s.queue.map(i=>i.id),preparedOrder);
  assert.equal((await repo.editQueue(begin)).status,'duplicate');
  s=(await repo.editQueue(command(s,{action:'remove',itemIds:preparedOrder}))).snapshot;
  assert.equal(s.queue.length,0);assert.equal(s.currentQueueItemId,null);assert.equal(s.playbackInstanceId,null);
  assert.equal(s.status,'stopped');assert.equal(s.positionMs,0);
  const emptyLate=await repo.update({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,
    anchor:anchor(s),leaseEpoch:s.leaseEpoch,status:'paused',renderPhase:'paused',positionMs:46000});
  assert.equal(emptyLate.status,'conflict');assert.deepEqual(emptyLate.snapshot,s);
  pass('prepared Play selects an existing entry once; removing the last clears execution and fences progress');
  s=await start();const originalInstance=s.playbackInstanceId;
  s=(await repo.editQueue(command(s,{action:'add',placement:'queue',trackRefs:[ref(4),ref(5)]}))).snapshot;
  s=(await repo.editQueue(command(s,{action:'add',placement:'queue',trackRefs:[ref(6)]}))).snapshot;
  assert.deepEqual(ids(s),['1','4','5','6','2','3']);
  s=(await repo.editQueue(command(s,{action:'add',placement:'next',trackRefs:[ref(7)]}))).snapshot;
  s=(await repo.editQueue(command(s,{action:'add',placement:'next',trackRefs:[ref(8)]}))).snapshot;
  s=(await repo.editQueue(command(s,{action:'add',placement:'end',trackRefs:[ref(9)]}))).snapshot;
  assert.deepEqual(ids(s),['1','8','7','4','5','6','2','3','9']);assert.equal(s.activeDeviceId,desktop);assert.equal(s.playbackInstanceId,originalInstance);
  pass('FIFO priority, immediate LIFO and final insertion match visible order; remote edits preserve owner');
  const frozen=command(s,{action:'add',placement:'queue',trackRefs:[ref(10)]});
  const progress=await repo.update({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,anchor:anchor(s),leaseEpoch:s.leaseEpoch,status:'playing',renderPhase:'playing',positionMs:12345});
  assert.equal(progress.status,'accepted');
  const afterProgress=await repo.editQueue(frozen);assert.equal(afterProgress.status,'accepted');s=afterProgress.snapshot;
  assert.equal(s.positionMs,12345);assert.equal(s.playbackInstanceId,originalInstance);assert.equal(s.activeDeviceId,desktop);
  const repeat=await repo.editQueue(frozen);assert.equal(repeat.status,'duplicate');assert.equal(repeat.snapshot.queue.length,s.queue.length);
  assert.equal((await repo.editQueue({...frozen,operation:{...frozen.operation,trackRefs:[ref(11)]}})).error.code,'COMMAND_ID_REUSED');
  pass('heartbeat cannot invalidate structural edit; exact retry once and changed payload denied');
  const concurrent=command(s,{action:'add',placement:'end',trackRefs:[ref(11)]});
  const races=await Promise.all([repo.editQueue(concurrent),repo.editQueue({...concurrent,commandId:randomUUID()})]);
  assert.equal(races.filter(r=>r.status==='accepted').length,1);s=await repo.snapshot(user);
  assert.equal((await repo.editQueue({...command(s,{action:'clear-upcoming'}),deviceId:foreign})).status,'conflict');
  pass('concurrent structural edits serialize and another user cannot mutate the queue');
  const oldSelect={userId:user,deviceId:mobile,commandId:randomUUID(),expectedRevision:s.revision,sourceId:source,remoteTrackIds:['20'],selectedIndex:0,contextType:'album',contextRef:'other'};
  const refused=await repo.selectContext(oldSelect);assert.equal(refused.error.code,'QUEUE_REPLACE_CONFIRMATION');assert.deepEqual(ids(refused.snapshot),ids(s));
  const staleConfirmation=s.queueRevision;
  s=(await repo.editQueue(command(s,{action:'add',placement:'end',trackRefs:[ref(12)]}))).snapshot;
  const again=await repo.selectContext({...oldSelect,commandId:randomUUID(),expectedRevision:s.revision,replaceQueueRevision:staleConfirmation});
  assert.equal(again.error.code,'QUEUE_REPLACE_CONFIRMATION');
  s=await start(['22']);
  assert.equal((await repo.selectContext({...oldSelect,commandId:randomUUID(),expectedRevision:s.revision,replaceQueueRevision:staleConfirmation})).error.code,'QUEUE_REPLACE_CONFIRMATION');
  pass('manual continuation requires replacement confirmation and revalidates its version');
  s=await start(['1','2','2','3']);assert.deepEqual(ids(s),['1','2','3']);const first=s.queue[1].id,second=s.queue[2].id;
  s=(await repo.editQueue(command(s,{action:'move',itemIds:[second],beforeId:first,priority:true}))).snapshot;
  assert.deepEqual(s.queue.map(i=>i.id).slice(1,3),[second,first]);assert.equal(s.queue.length,3);
  s=(await repo.editQueue(command(s,{action:'remove',itemIds:[second]}))).snapshot;
  assert.equal(s.queue.filter(i=>i.trackRef===ref(2)).length,1);assert.ok(s.queueUndo);
  const undo=s.queueUndo.id;
  s=(await repo.editQueue(command(s,{action:'undo',undoId:undo}))).snapshot;assert.equal(s.queue[1].id,second);
  pass('context keeps first occurrences; move/remove/undo preserve unique entries');
  s=(await repo.editQueue(command(s,{action:'clear-upcoming'}))).snapshot;const invalidUndo=s.queueUndo.id;
  assert.equal(s.queue.length,1);assert.equal(s.currentTrackRef,ref(1));
  s=(await repo.editQueue(command(s,{action:'add',placement:'end',trackRefs:[ref(4)]}))).snapshot;
  assert.equal((await repo.editQueue(command(s,{action:'undo',undoId:invalidUndo}))).error.code,'UNDO_EXPIRED');
  pass('clear preserves current; undo cannot roll back subsequent changes');
  const save={action:'from-queue',commandId:randomUUID(),name:'Saved queue',description:'',scope:'all',expectedQueueRevision:s.queueRevision,currentQueueItemId:s.currentQueueItemId};
  const list=await lists.command(user,save);assert.equal(list.added,2);assert.equal((await lists.page(user,list.playlistId)).items[1].track.id,ref(4));
  assert.deepEqual((await lists.page(user,list.playlistId)).items.map(i=>i.originQueueItemId),s.queue.map(i=>i.id));
  const savedCopy=await lists.command(user,{action:'duplicate',commandId:randomUUID(),playlistId:list.playlistId,expectedRevision:list.revision,name:'Independent copy'});
  assert.ok((await lists.page(user,savedCopy.playlistId)).items.every(i=>i.originQueueItemId===null));
  assert.deepEqual(await lists.command(user,save),list);
  const beforeSave=s;
  const jump=await repo.editQueue(command(s,{action:'select',itemId:s.queue[1].id}));assert.equal(jump.status,'accepted');s=jump.snapshot;
  assert.equal(s.activeDeviceId,desktop);assert.equal(s.queue.length,2);assert.notEqual(s.playbackInstanceId,beforeSave.playbackInstanceId);
  await assert.rejects(lists.command(user,{...save,commandId:randomUUID(),scope:'remaining'}),e=>e.code==='QUEUE_CHANGED');
  s=(await repo.editQueue(command(s,{action:'remove',itemIds:[s.currentQueueItemId]}))).snapshot;
  assert.equal(s.status,'stopped');assert.equal(s.currentQueueItemId,null);assert.equal(s.queue.length,1);
  assert.equal(s.queuePastCount,1);
  assert.equal((await repo.editQueue(command(s,{action:'clear-upcoming'}))).status,'conflict');
  await assert.rejects(lists.command(user,{...save,commandId:randomUUID(),expectedQueueRevision:s.queueRevision,currentQueueItemId:null,scope:'remaining'}),e=>e.code==='QUEUE_LIMIT');
  s=(await repo.editQueue(command(s,{action:'add',placement:'queue',trackRefs:[ref(8)]}))).snapshot;
  assert.deepEqual(ids(s),['1','8']);assert.equal(s.queuePastCount,1);assert.equal(s.status,'stopped');
  s=(await repo.editQueue(command(s,{action:'clear-upcoming'}))).snapshot;assert.deepEqual(ids(s),['1']);
  s=(await repo.editQueue(command(s,{action:'undo',undoId:s.queueUndo.id}))).snapshot;assert.deepEqual(ids(s),['1','8']);assert.equal(s.queuePastCount,1);
  pass('saving is coherent/idempotent; selecting preserves queue/player; removing final current stops instead of replaying previous');
  s=await start();const late=command(s,{action:'add',placement:'next',trackRefs:[ref(15)]});
  s=(await repo.control({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,action:'next',reason:'ended',positionMs:180000,anchor:anchor(s)})).snapshot;
  assert.equal((await repo.editQueue(late)).error.code,'QUEUE_CHANGED');
  const paused=await repo.control({userId:user,deviceId:mobile,commandId:randomUUID(),expectedRevision:s.revision,action:'pause',anchor:anchor(s)});s=paused.snapshot;
  s=(await repo.editQueue(command(s,{action:'add',placement:'next',trackRefs:[ref(16)]}))).snapshot;assert.equal(s.status,'paused');assert.equal(s.activeDeviceId,desktop);
  pass('natural-end race rejects old target and paused insertion never starts audio');
  s=await start(['1']);const lastEnd=command(s,{action:'add',placement:'next',trackRefs:[ref(15)]});
  s=(await repo.control({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,action:'next',reason:'ended',positionMs:180000,anchor:anchor(s)})).snapshot;
  assert.equal(s.status,'stopped');assert.equal((await repo.editQueue(lastEnd)).error.code,'QUEUE_CHANGED');
  pass('end of final item also fences pending insertion despite unchanged current occurrence');
  s=await start(['1','2','3']);
  s=(await repo.editQueue(command(s,{action:'remove',itemIds:[s.queue[2].id]}))).snapshot;const expired=s.queueUndo.id;
  await db.query(`UPDATE playback_sessions SET queue_undo=jsonb_set(queue_undo,'{expiresAt}',to_jsonb('2000-01-01T00:00:00.000Z'::text)) WHERE user_id=$1`,[user]);
  assert.equal((await repo.editQueue(command(s,{action:'undo',undoId:expired}))).error.code,'UNDO_EXPIRED');
  s=await start(['1','2','3']);s=(await repo.editQueue(command(s,{action:'remove',itemIds:[s.queue[2].id]}))).snapshot;const advancedUndo=s.queueUndo.id;
  s=(await repo.control({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,action:'next',reason:'ended',positionMs:180000,anchor:anchor(s)})).snapshot;
  assert.equal((await repo.editQueue(command(s,{action:'undo',undoId:advancedUndo}))).error.code,'UNDO_EXPIRED');
  pass('undo expires and cannot rewind a natural advance');
  s=await start(['1','2','3']);const stable=s;
  const failingDb={...db,transaction:fn=>db.transaction(client=>fn({...client,query:(sql,values)=>{
    if(sql.includes('INSERT INTO playback_activity_outbox'))throw new Error('simulated outbox failure');return client.query(sql,values);
  }}))};
  const failCommand=command(s,{action:'add',placement:'next',trackRefs:[ref(4)]});
  await assert.rejects(new PlaybackRepository(failingDb).editQueue(failCommand),/simulated outbox failure/);
  assert.deepEqual(await repo.snapshot(user),stable);
  assert.equal(Number((await db.query('SELECT count(*) FROM playback_command_receipts WHERE user_id=$1 AND command_id=$2',[user,failCommand.commandId])).rows[0].count),0);
  pass('outbox failure rolls back queue, revision and command receipt together');
  const playlist=await lists.command(user,{action:'create',commandId:randomUUID(),name:'Occurrences',description:''});
  const added=await lists.command(user,{action:'add',commandId:randomUUID(),playlistId:playlist.playlistId,expectedRevision:0,trackRefs:[ref(1),ref(1)],duplicates:'skip'});
  assert.equal(added.added,1);assert.equal(added.skipped,1);
  s=(await repo.selectPlaylist({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,replaceQueueRevision:s.queueRevision,
    playlistId:playlist.playlistId,playlistRevision:added.revision,itemId:null,shuffle:false})).snapshot;
  const page=await lists.page(user,playlist.playlistId);assert.deepEqual(s.queue.map(i=>i.playlistItemId),page.items.map(i=>i.id));
  pass('playlist-to-queue provenance survives deduplication');
  s=await start(['1']);const batch=Array.from({length:4999},(_,i)=>ref(i+2));const timing=performance.now();
  s=(await repo.editQueue(command(s,{action:'add',placement:'queue',trackRefs:batch}))).snapshot;
  assert.equal(s.queue.length,5000);assert.equal((await repo.editQueue(command(s,{action:'add',placement:'end',trackRefs:[ref(5001)]}))).error.code,'QUEUE_LIMIT');
  console.log(`METRIC add 4999: ${Math.round(performance.now()-timing)}ms, snapshot ${Buffer.byteLength(JSON.stringify(s))} bytes`);
  const {queue:_queue,...compact}=s;console.log(`METRIC compact progress: ${Buffer.byteLength(JSON.stringify(compact))} bytes`);
  pass('5000 capacity without truncation; overflow leaves all existing entries unchanged');
  await db.query(`INSERT INTO user_favorites(user_id,source_id,entity_type,remote_entity_id) SELECT $1,$2,'track',n::text FROM generate_series(1,501)n`,[user,source]);
  const favorites=await repo.selectFavorites({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,replaceQueueRevision:s.queueRevision,shuffle:false,trackRef:null});
  assert.equal(favorites.status,'accepted');assert.equal(favorites.snapshot.queue.length,501);
  pass('favorites resolve coherently on the server beyond the old 500-row page');
  const projector=new PlaybackActivityProjector(db,{info(){},warn(){}});while(await projector.runBatch()){}
  pass('all accepted queue changes project through existing durable activity pipeline');
  s=await start(['1','2','3']);
  s=(await repo.editQueue(command(s,{action:'add',placement:'queue',trackRefs:[ref(4)]}))).snapshot;
  s=(await repo.failure({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,anchor:anchor(s),
    failure:{code:'decode',phase:'stream',positionMs:1000,elapsedMs:100}})).snapshot;
  assert.equal(s.currentTrackRef,ref(4));assert.equal(s.activeDeviceId,desktop);
  pass('isolated audio failure follows the visible priority order, without transferring the player');
  s=await start(['1','2']);
  s=(await repo.update({userId:user,deviceId:desktop,commandId:randomUUID(),expectedRevision:s.revision,anchor:anchor(s),leaseEpoch:s.leaseEpoch,status:'playing',renderPhase:'playing',positionMs:2000})).snapshot;
  const removedCurrent=s.currentQueueItemId;
  s=(await repo.editQueue(command(s,{action:'remove',itemIds:[removedCurrent]}))).snapshot;
  while(await projector.runBatch()){}
  assert.equal(Number((await db.query(`SELECT count(*) FROM listen_events WHERE user_id=$1 AND queue_item_id=$2 AND event_type='skipped'`,[user,removedCurrent])).rows[0].count),0);
  assert.equal(s.currentTrackRef,ref(2));
  pass('removing a playing occurrence does not manufacture a dislike/skip listening event');
  console.log(`${count} advanced queue integration groups passed`);
}finally{await db.close();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
